create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  created_at timestamptz not null default now()
);

create table if not exists public.meeting_folders (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  color text,
  created_at timestamptz not null default now()
);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null default '',
  email text not null default ''
);

create table if not exists public.meetings (
  id bigint generated by default as identity primary key,
  title text not null,
  file_name text not null,
  report text not null,
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  folder_id bigint
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  meeting_id bigint not null,
  created_at timestamptz not null default now(),
  action text not null,
  responsible text,
  responsible_employee_id bigint,
  due_date date,
  status text not null default 'À faire',
  completed_at timestamptz
);

create table if not exists public.meeting_participants (
  id bigint generated by default as identity primary key,
  meeting_id bigint not null,
  employee_id bigint not null,
  created_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists full_name text,
  add column if not exists email text,
  add column if not exists created_at timestamptz not null default now();

alter table public.meeting_folders
  add column if not exists name text not null default '',
  add column if not exists description text,
  add column if not exists color text,
  add column if not exists created_at timestamptz not null default now();

alter table public.employees
  add column if not exists name text not null default '',
  add column if not exists role text not null default '',
  add column if not exists email text not null default '';

alter table public.meetings
  add column if not exists title text not null default '',
  add column if not exists file_name text not null default '',
  add column if not exists report text not null default '',
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists deleted_at timestamptz,
  add column if not exists folder_id bigint;

alter table public.tasks
  add column if not exists meeting_id bigint,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists action text not null default '',
  add column if not exists responsible text,
  add column if not exists responsible_employee_id bigint,
  add column if not exists due_date date,
  add column if not exists status text not null default 'À faire',
  add column if not exists completed_at timestamptz;

alter table public.meeting_participants
  add column if not exists meeting_id bigint,
  add column if not exists employee_id bigint,
  add column if not exists created_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'meetings_folder_id_fkey'
  ) then
    alter table public.meetings
      add constraint meetings_folder_id_fkey
      foreign key (folder_id)
      references public.meeting_folders(id)
      on delete set null;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'tasks_meeting_id_fkey'
  ) then
    alter table public.tasks
      add constraint tasks_meeting_id_fkey
      foreign key (meeting_id)
      references public.meetings(id)
      on delete cascade;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'tasks_responsible_employee_id_fkey'
  ) then
    alter table public.tasks
      add constraint tasks_responsible_employee_id_fkey
      foreign key (responsible_employee_id)
      references public.employees(id)
      on delete set null;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'meeting_participants_meeting_id_fkey'
  ) then
    alter table public.meeting_participants
      add constraint meeting_participants_meeting_id_fkey
      foreign key (meeting_id)
      references public.meetings(id)
      on delete cascade;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'meeting_participants_employee_id_fkey'
  ) then
    alter table public.meeting_participants
      add constraint meeting_participants_employee_id_fkey
      foreign key (employee_id)
      references public.employees(id)
      on delete cascade;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'meeting_participants_meeting_id_employee_id_key'
  ) then
    alter table public.meeting_participants
      add constraint meeting_participants_meeting_id_employee_id_key
      unique (meeting_id, employee_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'tasks_status_check'
  ) then
    alter table public.tasks
      add constraint tasks_status_check
      check (status in ('À faire', 'En cours', 'Fait'));
  end if;
end $$;

create index if not exists meeting_folders_created_at_idx
  on public.meeting_folders(created_at desc);

create index if not exists profiles_email_idx
  on public.profiles(email);

create index if not exists employees_name_idx
  on public.employees(name);

create index if not exists meetings_created_at_idx
  on public.meetings(created_at desc);

create index if not exists meetings_deleted_at_idx
  on public.meetings(deleted_at);

create index if not exists meetings_folder_id_idx
  on public.meetings(folder_id);

create index if not exists tasks_meeting_id_idx
  on public.tasks(meeting_id);

create index if not exists tasks_responsible_employee_id_idx
  on public.tasks(responsible_employee_id);

create index if not exists tasks_status_idx
  on public.tasks(status);

create index if not exists tasks_due_date_idx
  on public.tasks(due_date);

create index if not exists tasks_completed_at_idx
  on public.tasks(completed_at);

create index if not exists meeting_participants_meeting_id_idx
  on public.meeting_participants(meeting_id);

create index if not exists meeting_participants_employee_id_idx
  on public.meeting_participants(employee_id);
