create extension if not exists pgcrypto;

create table if not exists public.organizations (
  id bigint generated by default as identity primary key,
  name text not null,
  logo_url text,
  industry text,
  employee_count text,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  organization_id bigint references public.organizations(id) on delete set null,
  role text,
  first_name text,
  last_name text,
  full_name text,
  email text,
  avatar_url text,
  job_title text,
  company text,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

create table if not exists public.invitations (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  email text not null,
  first_name text,
  last_name text,
  job_title text,
  role text not null default 'COLLABORATEUR',
  token text not null unique,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '14 days'),
  accepted_at timestamptz,
  invited_by uuid references auth.users(id) on delete set null
);

create table if not exists public.meeting_folders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  organization_id bigint references public.organizations(id) on delete set null,
  name text not null,
  description text,
  color text,
  created_at timestamptz not null default now()
);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  organization_id bigint references public.organizations(id) on delete set null,
  name text not null,
  role text not null default '',
  email text not null default ''
);

create table if not exists public.meetings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  organization_id bigint references public.organizations(id) on delete set null,
  title text not null,
  file_name text not null,
  report text not null,
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  folder_id bigint
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  organization_id bigint references public.organizations(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  meeting_id bigint not null,
  created_at timestamptz not null default now(),
  action text not null,
  responsible text,
  responsible_employee_id bigint,
  due_date date,
  priority text not null default 'Normale',
  status text not null default 'À faire',
  completed_at timestamptz
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  actor_name text,
  action_type text not null,
  description text not null,
  entity_type text,
  entity_id bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.meeting_participants (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  organization_id bigint references public.organizations(id) on delete set null,
  meeting_id bigint not null,
  employee_id bigint not null,
  created_at timestamptz not null default now()
);

alter table public.organizations
  add column if not exists name text not null default '',
  add column if not exists logo_url text,
  add column if not exists industry text,
  add column if not exists employee_count text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists created_by uuid references auth.users(id) on delete set null;

alter table public.profiles
  add column if not exists organization_id bigint references public.organizations(id) on delete set null,
  add column if not exists role text,
  add column if not exists first_name text,
  add column if not exists last_name text,
  add column if not exists full_name text,
  add column if not exists email text,
  add column if not exists avatar_url text,
  add column if not exists job_title text,
  add column if not exists company text,
  add column if not exists status text not null default 'active',
  add column if not exists created_at timestamptz not null default now();

alter table public.invitations
  add column if not exists organization_id bigint references public.organizations(id) on delete cascade,
  add column if not exists email text not null default '',
  add column if not exists first_name text,
  add column if not exists last_name text,
  add column if not exists job_title text,
  add column if not exists role text not null default 'COLLABORATEUR',
  add column if not exists token text not null default encode(gen_random_bytes(32), 'hex'),
  add column if not exists status text not null default 'pending',
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists expires_at timestamptz not null default (now() + interval '14 days'),
  add column if not exists accepted_at timestamptz,
  add column if not exists invited_by uuid references auth.users(id) on delete set null;

alter table public.meeting_folders
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists organization_id bigint references public.organizations(id) on delete set null,
  add column if not exists name text not null default '',
  add column if not exists description text,
  add column if not exists color text,
  add column if not exists created_at timestamptz not null default now();

alter table public.employees
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists organization_id bigint references public.organizations(id) on delete set null,
  add column if not exists name text not null default '',
  add column if not exists role text not null default '',
  add column if not exists email text not null default '';

alter table public.meetings
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists organization_id bigint references public.organizations(id) on delete set null,
  add column if not exists title text not null default '',
  add column if not exists file_name text not null default '',
  add column if not exists report text not null default '',
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists deleted_at timestamptz,
  add column if not exists folder_id bigint;

alter table public.tasks
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists organization_id bigint references public.organizations(id) on delete set null,
  add column if not exists created_by uuid references auth.users(id) on delete set null,
  add column if not exists meeting_id bigint,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists action text not null default '',
  add column if not exists responsible text,
  add column if not exists responsible_employee_id bigint,
  add column if not exists due_date date,
  add column if not exists priority text not null default 'Normale',
  add column if not exists status text not null default 'À faire',
  add column if not exists completed_at timestamptz;

alter table public.activity_logs
  add column if not exists organization_id bigint references public.organizations(id) on delete cascade,
  add column if not exists actor_id uuid references auth.users(id) on delete set null,
  add column if not exists actor_name text,
  add column if not exists action_type text not null default '',
  add column if not exists description text not null default '',
  add column if not exists entity_type text,
  add column if not exists entity_id bigint,
  add column if not exists created_at timestamptz not null default now();

alter table public.meeting_participants
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists organization_id bigint references public.organizations(id) on delete set null,
  add column if not exists meeting_id bigint,
  add column if not exists employee_id bigint,
  add column if not exists created_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'meetings_folder_id_fkey'
  ) then
    alter table public.meetings
      add constraint meetings_folder_id_fkey
      foreign key (folder_id)
      references public.meeting_folders(id)
      on delete set null;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'tasks_meeting_id_fkey'
  ) then
    alter table public.tasks
      add constraint tasks_meeting_id_fkey
      foreign key (meeting_id)
      references public.meetings(id)
      on delete cascade;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'tasks_responsible_employee_id_fkey'
  ) then
    alter table public.tasks
      add constraint tasks_responsible_employee_id_fkey
      foreign key (responsible_employee_id)
      references public.employees(id)
      on delete set null;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'meeting_participants_meeting_id_fkey'
  ) then
    alter table public.meeting_participants
      add constraint meeting_participants_meeting_id_fkey
      foreign key (meeting_id)
      references public.meetings(id)
      on delete cascade;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'meeting_participants_employee_id_fkey'
  ) then
    alter table public.meeting_participants
      add constraint meeting_participants_employee_id_fkey
      foreign key (employee_id)
      references public.employees(id)
      on delete cascade;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'meeting_participants_meeting_id_employee_id_key'
  ) then
    alter table public.meeting_participants
      add constraint meeting_participants_meeting_id_employee_id_key
      unique (meeting_id, employee_id);
  end if;
end $$;

alter table public.tasks drop constraint if exists tasks_status_check;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'tasks_status_check'
  ) then
    alter table public.tasks
      add constraint tasks_status_check
      check (status in ('À faire', 'En cours', 'Terminée', 'En retard', 'Fait'));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'tasks_priority_check'
  ) then
    alter table public.tasks
      add constraint tasks_priority_check
      check (priority in ('Basse', 'Normale', 'Haute', 'Urgente'));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'profiles_role_check'
  ) then
    alter table public.profiles
      add constraint profiles_role_check
      check (role in ('ADMIN', 'MANAGER', 'COLLABORATEUR') or role is null);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'profiles_status_check'
  ) then
    alter table public.profiles
      add constraint profiles_status_check
      check (status in ('active', 'suspended'));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'invitations_role_check'
  ) then
    alter table public.invitations
      add constraint invitations_role_check
      check (role in ('ADMIN', 'MANAGER', 'COLLABORATEUR'));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'invitations_status_check'
  ) then
    alter table public.invitations
      add constraint invitations_status_check
      check (status in ('pending', 'accepted', 'expired', 'revoked'));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'invitations_token_key'
  ) then
    alter table public.invitations
      add constraint invitations_token_key unique (token);
  end if;
end $$;

create or replace function public.current_user_organization_id()
returns bigint
language sql
security definer
stable
set search_path = public
as $$
  select organization_id
  from public.profiles
  where id = auth.uid()
  limit 1
$$;

create or replace function public.current_user_organization_role()
returns text
language sql
security definer
stable
set search_path = public
as $$
  select role
  from public.profiles
  where id = auth.uid()
  limit 1
$$;

create or replace function public.get_invitation_by_token(invitation_token text)
returns table (
  id bigint,
  organization_id bigint,
  email text,
  first_name text,
  last_name text,
  job_title text,
  role text,
  token text,
  status text,
  created_at timestamptz,
  expires_at timestamptz,
  accepted_at timestamptz,
  invited_by uuid
)
language sql
security definer
stable
set search_path = public
as $$
  select
    invitations.id,
    invitations.organization_id,
    invitations.email,
    invitations.first_name,
    invitations.last_name,
    invitations.job_title,
    invitations.role,
    invitations.token,
    invitations.status,
    invitations.created_at,
    invitations.expires_at,
    invitations.accepted_at,
    invitations.invited_by
  from public.invitations
  where invitations.token = invitation_token
    and invitations.status in ('pending', 'accepted')
  limit 1
$$;

create or replace function public.create_organization_workspace(
  organization_name text,
  organization_industry text default null
)
returns public.organizations
language plpgsql
security definer
set search_path = public
as $$
declare
  created_organization public.organizations;
  current_email text;
  current_full_name text;
begin
  if auth.uid() is null then
    raise exception 'Utilisateur non connecté.';
  end if;

  if nullif(trim(organization_name), '') is null then
    raise exception 'Le nom de l’entreprise est obligatoire.';
  end if;

  current_email := coalesce(auth.jwt() ->> 'email', '');
  current_full_name := coalesce(
    auth.jwt() -> 'user_metadata' ->> 'full_name',
    split_part(current_email, '@', 1),
    ''
  );

  insert into public.organizations (
    name,
    industry,
    created_by
  )
  values (
    trim(organization_name),
    nullif(trim(organization_industry), ''),
    auth.uid()
  )
  returning * into created_organization;

  insert into public.profiles (
    id,
    organization_id,
    role,
    full_name,
    email,
    status
  )
  values (
    auth.uid(),
    created_organization.id,
    'ADMIN',
    current_full_name,
    current_email,
    'active'
  )
  on conflict (id) do update
    set organization_id = excluded.organization_id,
        role = 'ADMIN',
        full_name = coalesce(nullif(public.profiles.full_name, ''), excluded.full_name),
        email = coalesce(nullif(public.profiles.email, ''), excluded.email),
        status = 'active';

  return created_organization;
end;
$$;

create index if not exists organizations_created_at_idx
  on public.organizations(created_at desc);

create index if not exists organizations_created_by_idx
  on public.organizations(created_by);

create index if not exists meeting_folders_created_at_idx
  on public.meeting_folders(created_at desc);

create index if not exists meeting_folders_user_id_idx
  on public.meeting_folders(user_id);

create index if not exists meeting_folders_organization_id_idx
  on public.meeting_folders(organization_id);

create index if not exists profiles_email_idx
  on public.profiles(email);

create index if not exists profiles_organization_id_idx
  on public.profiles(organization_id);

create index if not exists profiles_status_idx
  on public.profiles(status);

create index if not exists invitations_organization_id_idx
  on public.invitations(organization_id);

create index if not exists invitations_email_idx
  on public.invitations(lower(email));

create index if not exists invitations_status_idx
  on public.invitations(status);

create index if not exists invitations_expires_at_idx
  on public.invitations(expires_at);

create index if not exists employees_name_idx
  on public.employees(name);

create index if not exists employees_user_id_idx
  on public.employees(user_id);

create index if not exists employees_organization_id_idx
  on public.employees(organization_id);

create index if not exists meetings_created_at_idx
  on public.meetings(created_at desc);

create index if not exists meetings_user_id_idx
  on public.meetings(user_id);

create index if not exists meetings_organization_id_idx
  on public.meetings(organization_id);

create index if not exists meetings_deleted_at_idx
  on public.meetings(deleted_at);

create index if not exists meetings_folder_id_idx
  on public.meetings(folder_id);

create index if not exists tasks_meeting_id_idx
  on public.tasks(meeting_id);

create index if not exists tasks_user_id_idx
  on public.tasks(user_id);

create index if not exists tasks_organization_id_idx
  on public.tasks(organization_id);

create index if not exists tasks_created_by_idx
  on public.tasks(created_by);

create index if not exists tasks_priority_idx
  on public.tasks(priority);

create index if not exists tasks_responsible_employee_id_idx
  on public.tasks(responsible_employee_id);

create index if not exists tasks_status_idx
  on public.tasks(status);

create index if not exists tasks_due_date_idx
  on public.tasks(due_date);

create index if not exists tasks_completed_at_idx
  on public.tasks(completed_at);

create index if not exists meeting_participants_meeting_id_idx
  on public.meeting_participants(meeting_id);

create index if not exists meeting_participants_user_id_idx
  on public.meeting_participants(user_id);

create index if not exists meeting_participants_organization_id_idx
  on public.meeting_participants(organization_id);

create index if not exists meeting_participants_employee_id_idx
  on public.meeting_participants(employee_id);

create index if not exists activity_logs_organization_id_created_at_idx
  on public.activity_logs(organization_id, created_at desc);

create index if not exists activity_logs_actor_id_idx
  on public.activity_logs(actor_id);

-- Migration temporaire pour rattacher les anciennes données à un utilisateur.
-- Remplace '00000000-0000-0000-0000-000000000000' par l'id auth.users souhaité,
-- puis exécute ces UPDATE une seule fois avant d'activer RLS en production.
--
-- update public.meeting_folders set user_id = '00000000-0000-0000-0000-000000000000' where user_id is null;
-- update public.employees set user_id = '00000000-0000-0000-0000-000000000000' where user_id is null;
-- update public.meetings set user_id = '00000000-0000-0000-0000-000000000000' where user_id is null;
-- update public.tasks set user_id = '00000000-0000-0000-0000-000000000000' where user_id is null;
-- update public.meeting_participants set user_id = '00000000-0000-0000-0000-000000000000' where user_id is null;
--
-- Pour rattacher ces anciennes données à une entreprise existante :
-- update public.profiles set organization_id = 1, role = 'ADMIN' where id = '00000000-0000-0000-0000-000000000000';
-- update public.meeting_folders set organization_id = 1 where organization_id is null;
-- update public.employees set organization_id = 1 where organization_id is null;
-- update public.meetings set organization_id = 1 where organization_id is null;
-- update public.tasks set organization_id = 1 where organization_id is null;
-- update public.meeting_participants set organization_id = 1 where organization_id is null;

alter table public.organizations enable row level security;
alter table public.meeting_folders enable row level security;
alter table public.profiles enable row level security;
alter table public.invitations enable row level security;
alter table public.employees enable row level security;
alter table public.meetings enable row level security;
alter table public.tasks enable row level security;
alter table public.meeting_participants enable row level security;
alter table public.activity_logs enable row level security;

drop policy if exists "Users can read own organizations" on public.organizations;
create policy "Users can read own organizations"
  on public.organizations for select
  using (
    created_by = auth.uid()
    or exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.organization_id = organizations.id
    )
  );

drop policy if exists "Users can create own organizations" on public.organizations;
create policy "Users can create own organizations"
  on public.organizations for insert
  with check (created_by = auth.uid());

drop policy if exists "Admins can update own organizations" on public.organizations;
create policy "Admins can update own organizations"
  on public.organizations for update
  using (
    created_by = auth.uid()
    or exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.organization_id = organizations.id
        and profiles.role = 'ADMIN'
    )
  )
  with check (
    created_by = auth.uid()
    or exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.organization_id = organizations.id
        and profiles.role = 'ADMIN'
    )
  );

drop policy if exists "Admins can delete own organizations" on public.organizations;
create policy "Admins can delete own organizations"
  on public.organizations for delete
  using (
    created_by = auth.uid()
    or exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.organization_id = organizations.id
        and profiles.role = 'ADMIN'
    )
  );

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
  on public.profiles for select
  using (
    auth.uid() = id
    or (
      organization_id is not null
      and organization_id = public.current_user_organization_id()
    )
  );

drop policy if exists "Users can create own profile" on public.profiles;
create policy "Users can create own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "Admins can update organization profiles" on public.profiles;
create policy "Admins can update organization profiles"
  on public.profiles for update
  using (
    organization_id = public.current_user_organization_id()
    and public.current_user_organization_role() = 'ADMIN'
  )
  with check (
    public.current_user_organization_role() = 'ADMIN'
    and (
      organization_id = public.current_user_organization_id()
      or organization_id is null
    )
  );

drop policy if exists "Users can delete own profile" on public.profiles;
create policy "Users can delete own profile"
  on public.profiles for delete
  using (auth.uid() = id);

drop policy if exists "Admins can read organization invitations" on public.invitations;
create policy "Admins can read organization invitations"
  on public.invitations for select
  using (
    organization_id = public.current_user_organization_id()
    and public.current_user_organization_role() = 'ADMIN'
  );

drop policy if exists "Invitees can read valid invitation by token" on public.invitations;

drop policy if exists "Admins can create organization invitations" on public.invitations;
create policy "Admins can create organization invitations"
  on public.invitations for insert
  with check (
    invited_by = auth.uid()
    and organization_id = public.current_user_organization_id()
    and public.current_user_organization_role() = 'ADMIN'
  );

drop policy if exists "Admins can update organization invitations" on public.invitations;
create policy "Admins can update organization invitations"
  on public.invitations for update
  using (
    organization_id = public.current_user_organization_id()
    and public.current_user_organization_role() = 'ADMIN'
  )
  with check (
    organization_id = public.current_user_organization_id()
    and public.current_user_organization_role() = 'ADMIN'
  );

drop policy if exists "Invitees can accept own invitation" on public.invitations;
create policy "Invitees can accept own invitation"
  on public.invitations for update
  using (
    status = 'pending'
    and expires_at > now()
    and lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  )
  with check (
    status = 'accepted'
    and lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );

drop policy if exists "Admins can delete organization invitations" on public.invitations;
create policy "Admins can delete organization invitations"
  on public.invitations for delete
  using (
    organization_id = public.current_user_organization_id()
    and public.current_user_organization_role() = 'ADMIN'
  );

drop policy if exists "Users can read own meeting folders" on public.meeting_folders;
create policy "Users can read own meeting folders"
  on public.meeting_folders for select
  using (auth.uid() = user_id);

drop policy if exists "Users can create own meeting folders" on public.meeting_folders;
create policy "Users can create own meeting folders"
  on public.meeting_folders for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own meeting folders" on public.meeting_folders;
create policy "Users can update own meeting folders"
  on public.meeting_folders for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own meeting folders" on public.meeting_folders;
create policy "Users can delete own meeting folders"
  on public.meeting_folders for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can read own employees" on public.employees;
create policy "Users can read own employees"
  on public.employees for select
  using (auth.uid() = user_id);

drop policy if exists "Users can create own employees" on public.employees;
create policy "Users can create own employees"
  on public.employees for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own employees" on public.employees;
create policy "Users can update own employees"
  on public.employees for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own employees" on public.employees;
create policy "Users can delete own employees"
  on public.employees for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can read own meetings" on public.meetings;
create policy "Users can read own meetings"
  on public.meetings for select
  using (auth.uid() = user_id);

drop policy if exists "Users can create own meetings" on public.meetings;
create policy "Users can create own meetings"
  on public.meetings for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own meetings" on public.meetings;
create policy "Users can update own meetings"
  on public.meetings for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own meetings" on public.meetings;
create policy "Users can delete own meetings"
  on public.meetings for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can read own tasks" on public.tasks;
create policy "Users can read own tasks"
  on public.tasks for select
  using (auth.uid() = user_id);

drop policy if exists "Users can create own tasks" on public.tasks;
create policy "Users can create own tasks"
  on public.tasks for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own tasks" on public.tasks;
create policy "Users can update own tasks"
  on public.tasks for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own tasks" on public.tasks;
create policy "Users can delete own tasks"
  on public.tasks for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can read own meeting participants" on public.meeting_participants;
create policy "Users can read own meeting participants"
  on public.meeting_participants for select
  using (auth.uid() = user_id);

drop policy if exists "Users can create own meeting participants" on public.meeting_participants;
create policy "Users can create own meeting participants"
  on public.meeting_participants for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own meeting participants" on public.meeting_participants;
create policy "Users can update own meeting participants"
  on public.meeting_participants for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own meeting participants" on public.meeting_participants;
create policy "Users can delete own meeting participants"
  on public.meeting_participants for delete
  using (auth.uid() = user_id);

-- SaaS collaboratif : toutes les données métier appartiennent à l'organisation.
drop policy if exists "Organization members can read meeting folders" on public.meeting_folders;
drop policy if exists "Managers can create meeting folders" on public.meeting_folders;
drop policy if exists "Managers can update meeting folders" on public.meeting_folders;
drop policy if exists "Managers can delete meeting folders" on public.meeting_folders;
drop policy if exists "Organization members can read employees" on public.employees;
drop policy if exists "Managers can create employees" on public.employees;
drop policy if exists "Managers can update employees" on public.employees;
drop policy if exists "Admins can delete employees" on public.employees;
drop policy if exists "Organization members can read meetings" on public.meetings;
drop policy if exists "Managers can create meetings" on public.meetings;
drop policy if exists "Managers can update meetings" on public.meetings;
drop policy if exists "Managers can delete meetings" on public.meetings;
drop policy if exists "Organization members can read tasks" on public.tasks;
drop policy if exists "Managers can create tasks" on public.tasks;
drop policy if exists "Organization members can update tasks" on public.tasks;
drop policy if exists "Managers can delete tasks" on public.tasks;
drop policy if exists "Organization members can read meeting participants" on public.meeting_participants;
drop policy if exists "Managers can create meeting participants" on public.meeting_participants;
drop policy if exists "Managers can update meeting participants" on public.meeting_participants;
drop policy if exists "Managers can delete meeting participants" on public.meeting_participants;
drop policy if exists "Managers can create organization invitations" on public.invitations;
drop policy if exists "Managers can read organization invitations" on public.invitations;

drop policy if exists "Users can read own meeting folders" on public.meeting_folders;
create policy "Organization members can read meeting folders"
  on public.meeting_folders for select
  using (organization_id = public.current_user_organization_id());

drop policy if exists "Users can create own meeting folders" on public.meeting_folders;
create policy "Managers can create meeting folders"
  on public.meeting_folders for insert
  with check (
    organization_id = public.current_user_organization_id()
    and auth.uid() = user_id
    and public.current_user_organization_role() in ('ADMIN', 'MANAGER')
  );

drop policy if exists "Users can update own meeting folders" on public.meeting_folders;
create policy "Managers can update meeting folders"
  on public.meeting_folders for update
  using (
    organization_id = public.current_user_organization_id()
    and public.current_user_organization_role() in ('ADMIN', 'MANAGER')
  )
  with check (organization_id = public.current_user_organization_id());

drop policy if exists "Users can delete own meeting folders" on public.meeting_folders;
create policy "Managers can delete meeting folders"
  on public.meeting_folders for delete
  using (
    organization_id = public.current_user_organization_id()
    and public.current_user_organization_role() in ('ADMIN', 'MANAGER')
  );

drop policy if exists "Users can read own employees" on public.employees;
create policy "Organization members can read employees"
  on public.employees for select
  using (organization_id = public.current_user_organization_id());

drop policy if exists "Users can create own employees" on public.employees;
create policy "Managers can create employees"
  on public.employees for insert
  with check (
    organization_id = public.current_user_organization_id()
    and auth.uid() = user_id
    and public.current_user_organization_role() in ('ADMIN', 'MANAGER')
  );

drop policy if exists "Users can update own employees" on public.employees;
create policy "Managers can update employees"
  on public.employees for update
  using (
    organization_id = public.current_user_organization_id()
    and public.current_user_organization_role() in ('ADMIN', 'MANAGER')
  )
  with check (organization_id = public.current_user_organization_id());

drop policy if exists "Users can delete own employees" on public.employees;
create policy "Admins can delete employees"
  on public.employees for delete
  using (
    organization_id = public.current_user_organization_id()
    and public.current_user_organization_role() = 'ADMIN'
  );

drop policy if exists "Users can read own meetings" on public.meetings;
create policy "Organization members can read meetings"
  on public.meetings for select
  using (organization_id = public.current_user_organization_id());

drop policy if exists "Users can create own meetings" on public.meetings;
create policy "Managers can create meetings"
  on public.meetings for insert
  with check (
    organization_id = public.current_user_organization_id()
    and auth.uid() = user_id
    and public.current_user_organization_role() in ('ADMIN', 'MANAGER')
  );

drop policy if exists "Users can update own meetings" on public.meetings;
create policy "Managers can update meetings"
  on public.meetings for update
  using (
    organization_id = public.current_user_organization_id()
    and public.current_user_organization_role() in ('ADMIN', 'MANAGER')
  )
  with check (organization_id = public.current_user_organization_id());

drop policy if exists "Users can delete own meetings" on public.meetings;
create policy "Managers can delete meetings"
  on public.meetings for delete
  using (
    organization_id = public.current_user_organization_id()
    and public.current_user_organization_role() in ('ADMIN', 'MANAGER')
  );

drop policy if exists "Users can read own tasks" on public.tasks;
create policy "Organization members can read tasks"
  on public.tasks for select
  using (organization_id = public.current_user_organization_id());

drop policy if exists "Users can create own tasks" on public.tasks;
create policy "Managers can create tasks"
  on public.tasks for insert
  with check (
    organization_id = public.current_user_organization_id()
    and auth.uid() = user_id
    and public.current_user_organization_role() in ('ADMIN', 'MANAGER')
  );

drop policy if exists "Users can update own tasks" on public.tasks;
create policy "Organization members can update tasks"
  on public.tasks for update
  using (organization_id = public.current_user_organization_id())
  with check (organization_id = public.current_user_organization_id());

drop policy if exists "Users can delete own tasks" on public.tasks;
create policy "Managers can delete tasks"
  on public.tasks for delete
  using (
    organization_id = public.current_user_organization_id()
    and public.current_user_organization_role() in ('ADMIN', 'MANAGER')
  );

drop policy if exists "Users can read own meeting participants" on public.meeting_participants;
create policy "Organization members can read meeting participants"
  on public.meeting_participants for select
  using (organization_id = public.current_user_organization_id());

drop policy if exists "Users can create own meeting participants" on public.meeting_participants;
create policy "Managers can create meeting participants"
  on public.meeting_participants for insert
  with check (
    organization_id = public.current_user_organization_id()
    and auth.uid() = user_id
    and public.current_user_organization_role() in ('ADMIN', 'MANAGER')
  );

drop policy if exists "Users can update own meeting participants" on public.meeting_participants;
create policy "Managers can update meeting participants"
  on public.meeting_participants for update
  using (
    organization_id = public.current_user_organization_id()
    and public.current_user_organization_role() in ('ADMIN', 'MANAGER')
  )
  with check (organization_id = public.current_user_organization_id());

drop policy if exists "Users can delete own meeting participants" on public.meeting_participants;
create policy "Managers can delete meeting participants"
  on public.meeting_participants for delete
  using (
    organization_id = public.current_user_organization_id()
    and public.current_user_organization_role() in ('ADMIN', 'MANAGER')
  );

drop policy if exists "Organization members can read activity logs" on public.activity_logs;
create policy "Organization members can read activity logs"
  on public.activity_logs for select
  using (organization_id = public.current_user_organization_id());

drop policy if exists "Organization members can create activity logs" on public.activity_logs;
create policy "Organization members can create activity logs"
  on public.activity_logs for insert
  with check (
    organization_id = public.current_user_organization_id()
    and actor_id = auth.uid()
  );

drop policy if exists "Admins can create organization invitations" on public.invitations;
create policy "Managers can create organization invitations"
  on public.invitations for insert
  with check (
    invited_by = auth.uid()
    and organization_id = public.current_user_organization_id()
    and public.current_user_organization_role() in ('ADMIN', 'MANAGER')
  );

drop policy if exists "Admins can read organization invitations" on public.invitations;
create policy "Managers can read organization invitations"
  on public.invitations for select
  using (
    organization_id = public.current_user_organization_id()
    and public.current_user_organization_role() in ('ADMIN', 'MANAGER')
  );

do $$
begin
  alter publication supabase_realtime add table public.meetings;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.tasks;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.meeting_folders;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.employees;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.profiles;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.activity_logs;
exception when duplicate_object then null;
end $$;
